name: com.cherish.mingji
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
   flutter:
    sdk: flutter
   dio: ^5.7.0
   go_router: ^14.2.8
   flutter_svg: ^2.0.10+1
   flutter_colorpicker: ^1.1.0
   hexcolor: ^3.0.1
   image_picker: ^1.1.2
   path_provider: ^2.1.4
   sqflite: ^2.3.3+1
   intl: ^0.19.0
   geolocator: ^13.0.1 
   modal_bottom_sheet: ^3.0.0
   shared_preferences: ^2.3.2
   archive: ^3.6.1
   file_picker: ^8.1.2
   permission_handler: ^11.3.1 
   share_plus: ^10.0.2
   flutter_localizations:
     sdk: flutter
   package_info_plus: ^8.0.2
   provider: ^6.1.2
   flutter_secure_storage: ^9.2.2   
   flutter_swiper_view: ^1.1.8  
   sign_in_with_apple: ^6.1.2
   flutter_styled_toast: ^2.2.1 
   connectivity_plus: ^6.0.5
   device_info_plus: ^10.1.2
   purchases_flutter: ^8.1.3 
   flex_color_scheme: ^7.3.1
   lunar: ^1.7.0
   sqflite_sqlcipher: ^3.1.0+1
   purchases_ui_flutter: ^8.1.3   
   cached_network_image: ^3.4.1
   flutter_client_sse: ^2.0.3
   google_fonts: ^6.2.1
   image_cropper: ^8.0.2  
   url_launcher: ^6.3.0  
   flutter_easyloading: ^3.0.5 
   chat_bottom_container: ^0.2.0
   wechat_assets_picker: ^9.3.3
   wechat_camera_picker: ^4.3.3
   lottie: ^3.1.3
   loading_animation_widget: ^1.3.0
   easy_date_timeline: ^1.1.3
   timeago: ^3.7.0
   screenshot: ^3.0.0
   haptic_feedback: ^0.5.1+1
   open_file: ^3.5.9
   video_player: ^2.9.2   
   image: ^4.3.0
   flutter_swipe_action_cell: ^3.1.5
   fl_chart: ^0.69.0
   upgrader: ^11.3.0 
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/icons/ # 子目录的路径也要写上，或者指定为目标文件的路径
    - assets/svg/ # 子目录的路径也要写上，或者指定为目标文件的路径
    - assets/header.jpg # 子目录的路径也要写上，或者指定为目标文件的路径
    - assets/images/ # 子目录的路径也要写上，或者指定为目标文件的路径
    - assets/weather/icons/ # 子目录的路径也要写上，或者指定为目标文件的路径
 
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: assets/fonts/AlibabaPuHuiTi-3-55-Regular.ttf
    - family: HarmonyOS_Sans_SC_Regular
      fonts:
        - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf
flutter_intl:
  enabled: true